name: Test

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEVELOPER_DIR: "/Applications/Xcode_15.0.1.app/Contents/Developer"

jobs:
  unit_test:
    name: Test
    runs-on: macos-13
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: Run Test
        run: |
          swift test | xcbeautify